#ifndef LAMP_KERNEL_PLATFORM_H
#define LAMP_KERNEL_PLATFORM_H

#include "types.h"

#define KERNEL_MEM_SIZE 0x04000000u
#define USER_REGION_BASE 0x02000000u
#define USER_REGION_SIZE 0x01000000u
#define USER_STACK_TOP (USER_REGION_BASE + USER_REGION_SIZE)
#define USER_STACK_RESERVE 0x00080000u
#define KERNEL_IRQ_STACK_SHIFT 15u
#define KERNEL_IRQ_STACK_BYTES (1u << KERNEL_IRQ_STACK_SHIFT)
#define KERNEL_IRQ_STACK_TOP (USER_REGION_BASE - 0x00010000u)
#define KERNEL_IVT_SIZE 256u
#define KERNEL_IVT_BASE 0x00000000u
#define KERNEL_IVT_ENTRY_SIZE 8u
#define KERNEL_LOG_LEVEL_DEFAULT 3u

#define FB_WIDTH 640u
#define FB_HEIGHT 480u
#define FB_BPP 4u
#define FB_SIZE (FB_WIDTH * FB_HEIGHT * FB_BPP)
#define FB_BASE KERNEL_MEM_SIZE

#define IO_SERIAL_TX 0x01u
#define IO_SERIAL_STATUS 0x02u
#define IO_SERIAL_RX 0x03u
#define IO_PS2_KBD_STATUS 0x04u
#define IO_PS2_KBD_DATA 0x05u
#define IO_PS2_MOUSE_STATUS 0x06u
#define IO_PS2_MOUSE_DATA 0x07u
#define IO_FB_ACCEL_ARG0 0x08u
#define IO_FB_ACCEL_CMD 0x09u
#define IO_PS2_DATA 0x60u
#define IO_PS2_STATUS 0x64u
#define IO_PS2_COMMAND 0x64u
#define IO_DISK_CMD 0x10u
#define IO_DISK_LBA 0x11u
#define IO_DISK_MEM 0x12u
#define IO_DISK_COUNT 0x13u
#define IO_DISK_STATUS 0x14u
#define IO_CPU_CTX_CSP 0xF0u
#define IO_CPU_CTX_DSP 0xF1u
#define IO_CPU_CTX_IRQ_MASK 0xF2u
#define IO_CPU_CTX_ISP 0xF3u
#define IO_CPU_CTX_CALL_BASE 0xF4u
#define IO_CPU_CTX_DATA_BASE 0xF5u
#define IO_CPU_CTX_ISR_BASE 0xF6u
#define IO_CPU_CTX_IN_INTERRUPT 0xF7u

#define SERIAL_STATUS_RX_READY 0x01u
#define SERIAL_CTRL_RX_INT_ENABLE 0x01u
#define PS2_STATUS_RX_READY 0x01u
#define PS2_STATUS_OUT_FULL 0x01u
#define PS2_STATUS_IN_FULL 0x02u
#define PS2_STATUS_AUX_DATA 0x20u
#define FB_ACCEL_CMD_SCROLL_UP_8PX 0x01u
#define FB_ACCEL_CMD_CLEAR 0x02u
#define DISK_STATUS_FREE 0x00u
#define DISK_STATUS_BUSY 0x01u
#define DISK_STATUS_ERROR 0x02u
#define DISK_CMD_READ 0x01u
#define DISK_CMD_WRITE 0x02u

#define VM_CALL_STACK_BASE 0x00000800u
#define VM_CALL_STACK_ENTRIES 256u
#define VM_CALL_STACK_BYTES (VM_CALL_STACK_ENTRIES * 8u)
#define VM_DATA_STACK_BASE 0x00001000u
#define VM_DATA_STACK_ENTRIES 256u
#define VM_DATA_STACK_BYTES (VM_DATA_STACK_ENTRIES * 4u)
#define VM_ISR_STACK_BASE 0x00001800u
#define VM_ISR_STACK_ENTRIES 256u
#define VM_ISR_STACK_BYTES (VM_ISR_STACK_ENTRIES * 8u)
#define VM_ARCH_STACK_SLOT_BYTES (VM_CALL_STACK_BYTES + VM_DATA_STACK_BYTES + VM_ISR_STACK_BYTES)
#define VM_TASK_C_STACK_BYTES KERNEL_IRQ_STACK_BYTES
#define VM_STACK_SLOT_BYTES (VM_ARCH_STACK_SLOT_BYTES + VM_TASK_C_STACK_BYTES)
#define VM_STACK_POOL_SLOTS 64u
#define VM_STACK_POOL_BYTES (VM_STACK_SLOT_BYTES * VM_STACK_POOL_SLOTS)
#define VM_STACK_POOL_BASE (KERNEL_MEM_SIZE - VM_STACK_POOL_BYTES)

#define IRQ_KEYBOARD 0x00u
#define IRQ_DIVIDE_BY_ZERO 0x01u
#define IRQ_DISK_COMPLETE 0x02u
#define IRQ_SERIAL 0x03u
#define IRQ_TIMER 0x04u
#define IRQ_MOUSE 0x05u
#define IRQ_SYSCALL 0x80u
#define IRQ_USER_EXEC_ENTER 0x81u

#define TIMER_MMIO_BASE 0x00002000u

#define SYSINFO_MMIO_BASE 0x0074C000u
#define INTC_MMIO_BASE 0x0074D000u
#define INTC_REG_PENDING 0x000u
#define INTC_REG_ENABLE 0x040u
#define INTC_REG_PRIORITY 0x100u
#define INTC_REG_EOI 0x500u
#define IOMMU_MMIO_BASE 0x0074E000u
#define IOMMU_REG_CAP 0x000u
#define IOMMU_REG_CTRL 0x004u
#define IOMMU_REG_DEVSEL 0x008u
#define IOMMU_REG_DEV_CTRL 0x00Cu
#define IOMMU_REG_IOVA_BASE_LO 0x010u
#define IOMMU_REG_IOVA_BASE_HI 0x014u
#define IOMMU_REG_IOVA_SIZE 0x018u
#define IOMMU_REG_PA_BASE_LO 0x01Cu
#define IOMMU_REG_PA_BASE_HI 0x020u
#define IOMMU_REG_FAULT_STATUS 0x024u
#define IOMMU_REG_FAULT_DEV 0x028u
#define IOMMU_REG_FAULT_IOVA_LO 0x02Cu
#define IOMMU_REG_FAULT_IOVA_HI 0x030u
#define IOMMU_REG_FAULT_LEN 0x034u
#define MMU_MMIO_BASE 0x0074F000u
#define MMU_REG_CAP 0x000u
#define MMU_REG_CTRL 0x004u
#define MMU_REG_ROOT_LO 0x008u
#define MMU_REG_ROOT_HI 0x00Cu
#define MMU_REG_FAULT_STATUS 0x010u
#define MMU_REG_FAULT_ADDR_LO 0x014u
#define MMU_REG_FAULT_ADDR_HI 0x018u
#define MMU_REG_FAULT_INFO 0x01Cu
#define SYSINFO_MAGIC 0x31494D56u /* "VMI1" */
#define SYSINFO_LAYOUT_VERSION 2u

#define BOOTINFO_ADDR 0x002FF000u
#define BOOTINFO_MAGIC 0x3049424Cu /* "LBI0" */
#define BOOTINFO_VERSION 2u
#define BOOTINFO_SIZE 0x64u

#define BOOTINFO_ARCH_LAMP32 1u
#define BOOTINFO_ENDIAN_LITTLE 1u

#define BOOTINFO_FEATURE_TIME_MMIO (1u << 0)
#define BOOTINFO_FEATURE_FB_MMIO (1u << 1)
#define BOOTINFO_FEATURE_DISK_IO (1u << 2)
#define BOOTINFO_FEATURE_SMP (1u << 3)
#define BOOTINFO_FEATURE_TIMER_IRQ (1u << 4)
#define BOOTINFO_FEATURE_INTC_MMIO (1u << 5)
#define BOOTINFO_FEATURE_IOMMU_MMIO (1u << 6)
#define BOOTINFO_FEATURE_MMU_PAGING (1u << 7)

#define SYSCALL_ABI_ADDR 0x002FE000u
#define SYSCALL_ABI_MAGIC 0x30435953u /* "SYC0" */
#define SYSCALL_ABI_VERSION 1u

#endif
