#ifndef LAMP_USER_ABI_H
#define LAMP_USER_ABI_H

#include "types.h"

enum {
    LAMP_SYS_GETPID = 0u,
    LAMP_SYS_YIELD = 1u,
    LAMP_SYS_SLEEP_TICKS = 2u,
    LAMP_SYS_EXIT = 3u,
    LAMP_SYS_WAITPID = 4u,
    LAMP_SYS_NANOSLEEP = 5u,
    LAMP_SYS_READ = 6u,
    LAMP_SYS_WRITE = 7u,
    LAMP_SYS_POLL = 8u,
    LAMP_SYS_SELECT = 9u,
    LAMP_SYS_TTY_GETMODE = 10u,
    LAMP_SYS_TTY_SETMODE = 11u,
    LAMP_SYS_CLOCK_GETTIME = 12u,
    LAMP_SYS_GETTIMEOFDAY = 13u,
    LAMP_SYS_CLOCK_GETRES = 14u,
    LAMP_SYS_CLOCK_SETTIME = 15u,
    LAMP_SYS_CLOSE = 16u,
    LAMP_SYS_DUP = 17u,
    LAMP_SYS_DUP2 = 18u,
    LAMP_SYS_FCNTL = 19u,
    LAMP_SYS_OPEN = 20u,
    LAMP_SYS_SOCKET = 21u,
    LAMP_SYS_CONNECT = 22u,
    LAMP_SYS_BIND = 23u,
    LAMP_SYS_LISTEN = 24u,
    LAMP_SYS_ACCEPT = 25u,
    LAMP_SYS_SEND = 26u,
    LAMP_SYS_RECV = 27u,
    LAMP_SYS_EXECVE = 28u,
    LAMP_SYS_VFORK = 29u
};

enum {
    LAMP_ERRNO_OK = 0u,
    LAMP_ERRNO_ENOENT = 2u,
    LAMP_ERRNO_EINTR = 4u,
    LAMP_ERRNO_EIO = 5u,
    LAMP_ERRNO_EBADF = 9u,
    LAMP_ERRNO_ECHILD = 10u,
    LAMP_ERRNO_EAGAIN = 11u,
    LAMP_ERRNO_ENOMEM = 12u,
    LAMP_ERRNO_EFAULT = 14u,
    LAMP_ERRNO_EBUSY = 16u,
    LAMP_ERRNO_ENOTDIR = 20u,
    LAMP_ERRNO_EISDIR = 21u,
    LAMP_ERRNO_EINVAL = 22u,
    LAMP_ERRNO_EMFILE = 24u,
    LAMP_ERRNO_ENOSPC = 28u,
    LAMP_ERRNO_EROFS = 30u,
    LAMP_ERRNO_ENOSYS = 38u,
    LAMP_ERRNO_EOVERFLOW = 75u,
    LAMP_ERRNO_ENOTSOCK = 88u,
    LAMP_ERRNO_EOPNOTSUPP = 95u,
    LAMP_ERRNO_EAFNOSUPPORT = 97u,
    LAMP_ERRNO_ENOTCONN = 107u
};

enum {
    LAMP_IRQ_SYSCALL = 0x80u
};

enum {
    LAMP_SYSCALL_ABI_ADDR = 0x002FE000u,
    LAMP_SYSCALL_ABI_OFF_RET = 0x24u,
    LAMP_SYSCALL_ABI_OFF_ERRNO = 0x28u
};

#endif
