#ifndef LAMPVM_DEVICE_ABI_H
#define LAMPVM_DEVICE_ABI_H

#include <stdint.h>

/* Project-local PCI IDs. */
#define LAMP_PCI_VENDOR_ID 0x1DB7u
#define LAMP_PCI_GPU_DEVICE_ID 0x2000u
#define LAMP_PCI_AUDIO_DEVICE_ID 0x3000u

/* ---- Lamp PCI dumb-display v1 ---- */
#define LAMP_GPU_MAGIC 0x3147504Cu /* "LPG1" */
#define LAMP_GPU_VERSION 1u
#define LAMP_GPU_BAR0_SIZE 0x1000u
#define LAMP_GPU_VRAM_SIZE 0x00400000u
#define LAMP_GPU_FORMAT_XRGB8888 1u

enum {
    LAMP_GPU_REG_MAGIC = 0x000u,
    LAMP_GPU_REG_VERSION = 0x004u,
    LAMP_GPU_REG_CAPS = 0x008u,
    LAMP_GPU_REG_STATUS = 0x00Cu,
    LAMP_GPU_REG_WIDTH = 0x010u,
    LAMP_GPU_REG_HEIGHT = 0x014u,
    LAMP_GPU_REG_STRIDE = 0x018u,
    LAMP_GPU_REG_FORMAT = 0x01Cu,
    LAMP_GPU_REG_VRAM_SIZE = 0x020u,
    LAMP_GPU_REG_SCANOUT_OFFSET = 0x024u,
    LAMP_GPU_REG_PENDING_OFFSET = 0x028u,
    LAMP_GPU_REG_DAMAGE_X = 0x02Cu,
    LAMP_GPU_REG_DAMAGE_Y = 0x030u,
    LAMP_GPU_REG_DAMAGE_W = 0x034u,
    LAMP_GPU_REG_DAMAGE_H = 0x038u,
    LAMP_GPU_REG_COMMAND = 0x03Cu,
    LAMP_GPU_REG_SUBMIT_SEQ = 0x040u,
    LAMP_GPU_REG_COMPLETE_SEQ = 0x044u,
    LAMP_GPU_REG_IRQ_STATUS = 0x048u,
    LAMP_GPU_REG_IRQ_ENABLE = 0x04Cu,
    LAMP_GPU_REG_IRQ_ACK = 0x050u,
    LAMP_GPU_REG_CURSOR_X = 0x054u,
    LAMP_GPU_REG_CURSOR_Y = 0x058u,
    LAMP_GPU_REG_CURSOR_CTRL = 0x05Cu
};

#define LAMP_GPU_CAP_DAMAGE (1u << 0)
#define LAMP_GPU_CAP_PAGE_FLIP (1u << 1)
#define LAMP_GPU_CAP_MSI (1u << 2)
#define LAMP_GPU_CAP_SHADOW_SCANOUT (1u << 3)
#define LAMP_GPU_CAP_CURSOR (1u << 4)

#define LAMP_GPU_STATUS_READY (1u << 0)
#define LAMP_GPU_STATUS_ENABLED (1u << 1)
#define LAMP_GPU_STATUS_BAD_COMMAND (1u << 2)
#define LAMP_GPU_STATUS_BAD_SCANOUT (1u << 3)

#define LAMP_GPU_CMD_ENABLE (1u << 0)
#define LAMP_GPU_CMD_DISABLE (1u << 1)
#define LAMP_GPU_CMD_FLUSH (1u << 2)
#define LAMP_GPU_CMD_PAGE_FLIP (1u << 3)
#define LAMP_GPU_CMD_RESET (1u << 4)
#define LAMP_GPU_CMD_CURSOR_UPDATE (1u << 5)

#define LAMP_GPU_CURSOR_VISIBLE (1u << 0)
#define LAMP_GPU_CURSOR_BUTTONS_SHIFT 8u
#define LAMP_GPU_CURSOR_BUTTONS_MASK (7u << LAMP_GPU_CURSOR_BUTTONS_SHIFT)
#define LAMP_GPU_CURSOR_WIDTH 12u
#define LAMP_GPU_CURSOR_HEIGHT 18u

#define LAMP_GPU_IRQ_FLUSH_COMPLETE (1u << 0)
#define LAMP_GPU_IRQ_FLIP_COMPLETE (1u << 1)
#define LAMP_GPU_IRQ_ERROR (1u << 2)

/* ---- Reusable DMA submission/completion ring v1 ---- */
#define LAMP_DMA_RING_VERSION 1u
#define LAMP_DMA_RING_MIN_COUNT 2u
#define LAMP_DMA_RING_MAX_COUNT 256u

#define LAMP_DMA_DESC_F_IRQ (1u << 0)
#define LAMP_DMA_DESC_F_END (1u << 1)

#define LAMP_DMA_COMPLETION_OK 0u
#define LAMP_DMA_COMPLETION_BAD_DESC 1u
#define LAMP_DMA_COMPLETION_DMA_FAULT 2u
#define LAMP_DMA_COMPLETION_BACKEND_ERROR 3u

typedef struct lamp_dma_desc {
    uint32_t addr_lo;
    uint32_t addr_hi;
    uint32_t length;
    uint32_t flags;
    uint32_t cookie;
    uint32_t reserved0;
    uint32_t reserved1;
    uint32_t reserved2;
} lamp_dma_desc_t;

typedef struct lamp_dma_completion {
    uint32_t cookie;
    uint32_t status;
    uint32_t bytes;
    uint32_t sequence;
} lamp_dma_completion_t;

/* ---- Lamp PCI PCM-audio v1 ---- */
#define LAMP_AUDIO_MAGIC 0x3141504Cu /* "LPA1" */
#define LAMP_AUDIO_VERSION 1u
#define LAMP_AUDIO_BAR0_SIZE 0x1000u
#define LAMP_AUDIO_RATE 48000u
#define LAMP_AUDIO_CHANNELS 2u
#define LAMP_AUDIO_SAMPLE_BITS 16u
#define LAMP_AUDIO_FRAME_BYTES 4u
#define LAMP_AUDIO_MAX_BUFFER_BYTES 65536u

enum {
    LAMP_AUDIO_REG_MAGIC = 0x000u,
    LAMP_AUDIO_REG_VERSION = 0x004u,
    LAMP_AUDIO_REG_CAPS = 0x008u,
    LAMP_AUDIO_REG_STATUS = 0x00Cu,
    LAMP_AUDIO_REG_RATE = 0x010u,
    LAMP_AUDIO_REG_CHANNELS = 0x014u,
    LAMP_AUDIO_REG_SAMPLE_BITS = 0x018u,
    LAMP_AUDIO_REG_FRAME_BYTES = 0x01Cu,
    LAMP_AUDIO_REG_SUBMIT_BASE_LO = 0x020u,
    LAMP_AUDIO_REG_SUBMIT_BASE_HI = 0x024u,
    LAMP_AUDIO_REG_SUBMIT_COUNT = 0x028u,
    LAMP_AUDIO_REG_SUBMIT_HEAD = 0x02Cu,
    LAMP_AUDIO_REG_SUBMIT_TAIL = 0x030u,
    LAMP_AUDIO_REG_COMPLETE_BASE_LO = 0x034u,
    LAMP_AUDIO_REG_COMPLETE_BASE_HI = 0x038u,
    LAMP_AUDIO_REG_COMPLETE_COUNT = 0x03Cu,
    LAMP_AUDIO_REG_COMPLETE_HEAD = 0x040u,
    LAMP_AUDIO_REG_COMPLETE_TAIL = 0x044u,
    LAMP_AUDIO_REG_COMMAND = 0x048u,
    LAMP_AUDIO_REG_IRQ_STATUS = 0x04Cu,
    LAMP_AUDIO_REG_IRQ_ENABLE = 0x050u,
    LAMP_AUDIO_REG_IRQ_ACK = 0x054u,
    LAMP_AUDIO_REG_QUEUED_BYTES = 0x058u,
    LAMP_AUDIO_REG_COMPLETED_DESCS = 0x05Cu
};

#define LAMP_AUDIO_CAP_PLAYBACK (1u << 0)
#define LAMP_AUDIO_CAP_DMA_RING (1u << 1)
#define LAMP_AUDIO_CAP_COMPLETION_RING (1u << 2)
#define LAMP_AUDIO_CAP_MSI (1u << 3)
#define LAMP_AUDIO_CAP_IOMMU (1u << 4)

#define LAMP_AUDIO_STATUS_READY (1u << 0)
#define LAMP_AUDIO_STATUS_RUNNING (1u << 1)
#define LAMP_AUDIO_STATUS_BACKEND_UNAVAILABLE (1u << 2)
#define LAMP_AUDIO_STATUS_RING_ERROR (1u << 3)
#define LAMP_AUDIO_STATUS_COMPLETION_FULL (1u << 4)
#define LAMP_AUDIO_STATUS_DMA_FAULT (1u << 5)

#define LAMP_AUDIO_CMD_ENABLE (1u << 0)
#define LAMP_AUDIO_CMD_DISABLE (1u << 1)
#define LAMP_AUDIO_CMD_RESET (1u << 2)

#define LAMP_AUDIO_IRQ_COMPLETION (1u << 0)
#define LAMP_AUDIO_IRQ_ERROR (1u << 1)

#endif /* LAMPVM_DEVICE_ABI_H */
